[package]
name = "egui-miniquad"
version = "0.7.0"
authors = ["Logachev Fedor <not.fl3@gmail.com>", "Emil Ernerfeldt <emil.ernerfeldt@gmail.com>"]
description = "Bindings between egui and miniquad"
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/not-fl3/egui-miniquad"
repository = "https://github.com/not-fl3/egui-miniquad"
categories = ["gui", "game-development"]
keywords = ["gui", "imgui", "immediate", "portable", "gamedev"]
include = [
  "../LICENSE-APACHE",
  "../LICENSE-MIT",
  "**/*.rs",
  "Cargo.toml",
]

[dependencies]
egui = "0.15.0"
miniquad = { version = "=0.3.0-alpha.37" }
quad-url = "0.1.0"

[dev-dependencies]
egui_demo_lib = { version = "0.15.0", default-features = false }
glam = "0.19"

[profile.release]
opt-level = 2 # fast and small wasm
